/*
 * generated by Xtext
 */
package de.itemis.mpp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPomValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.itemis.mpp.pom.PomPackage.eINSTANCE);
		return result;
	}
}
