/*
 * generated by Xtext
 */
package de.itemis.mpp;

import de.itemis.mpp.PomStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PomStandaloneSetup extends PomStandaloneSetupGenerated{

	public static void doSetup() {
		new PomStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

