/*
 * generated by Xtext
 */
package de.itemis.mpp;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PomUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.itemis.mpp.ui.internal.PomActivator.getInstance().getInjector("de.itemis.mpp.Pom");
	}
	
}
