/*
 * generated by Xtext
 */
package de.itemis.mpp.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.itemis.mpp.ui.internal.PomActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PomExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PomActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PomActivator.getInstance().getInjector(PomActivator.DE_ITEMIS_MPP_POM);
	}
	
}
