/*
 * generated by Xtext
 */
package de.itemis.mpp.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.itemis.mpp.services.PomGrammarAccess;

public class PomParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PomGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.itemis.mpp.parser.antlr.internal.InternalPomParser createParser(XtextTokenStream stream) {
		return new de.itemis.mpp.parser.antlr.internal.InternalPomParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "POM";
	}
	
	public PomGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PomGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
