/*
 * generated by Xtext
 */
package de.itemis.mpp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PomUiModule extends de.itemis.mpp.ui.AbstractPomUiModule {
	public PomUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
